name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: pnpm/action-setup@v4
        with:
          version: 8.x # Specify the pnpm version

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/

      - run: pnpm add -g @antfu/ni
      
      - run: pnpm install

    #   - run: pnpm exec changelogithub
    #     env:
    #       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          
      - run: pnpm run build
      
      - run: cd dist && pnpm exec vsce publish -p ${{secrets.VSCE_PAT}} --no-dependencies
        env:
          VSCE_TOKEN: ${{secrets.VSCE_PAT}}
      
      # Uncomment this block if publishing to OpenVSX:
      # - run: cd dist && pnpm exec ovsx publish -p ${{secrets.OVSX_TOKEN}} --no-dependencies
      #   env:
      #     OVSX_TOKEN: ${{secrets.OVSX_TOKEN}}
