name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      - run: npx conventional-github-releaser -p angular
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: yarn run build
      - run: cd build/icons-carbon && npx vsce publish -p ${{secrets.VSCE_PAT}}
        env:
          VSCE_TOKEN: ${{secrets.VSCE_PAT}}
      # - run: cd build/icons-carbon && npx ovsx publish -p ${{secrets.OVSX_TOKEN}}
      #   env:
      #     OVSX_TOKEN: ${{secrets.OVSX_TOKEN}}