name: Release VSCode Extension

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # Step 3: 安装依赖
      - name: Install dependencies
        run: |
          pnpm install
          pnpm add -g vsce  # 安装 vsce 用于发布

      # Step 4: 构建扩展
      - name: Build extension
        run: pnpm run build  # 执行构建命令

      # Step 5: 检查构建输出
      - name: Check output
        run: |
          ls dist  # 确保构建文件存在

      # Step 6: 打包并发布到 Visual Studio Code Marketplace
      - name: Publish to Visual Studio Code Marketplace
        run: |
          pnpm exec vsce package  # 打包为 .vsix 文件
          pnpm exec vsce publish -p ${{ secrets.VSCE_PAT }} --no-dependencies  # 发布到 Marketplace
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_PAT }}
